### ISSUE TITLE
API error when providing credentials for Connection object.

### ISSUE THREAD

**Issue by rhytnen** [AllenInstitute/pigeon#2]
The API pigeon is using to call [connect()](https://github.com/AllenInstitute/pigeon/blob/master/pigeon/client.py#L108) is incorrect because they are being passed in as keyword arguments and not positional arguments.

It isn't intuitive from the `Protocol12.connect()` code since it does refer to keyword arguments, but the STOMP documentation does use positional arguments like so: `conn.connect(username, password, wait=True)`.

They keyword arguments may in fact work, but STOMP uses the keyword `passcode` rather than `password`.

This bug results in an authentication error when you have anonymous usage turned off on the artemis server but will not generate an error otherwise.

**Comment by CameronDevine** [comment]
Looking at the source code for `Protocol12.connect()`, the function does use keyword arguments for the username and **passcode**.

https://github.com/jasonrbriggs/stomp.py/blob/dev/stomp/protocol.py#L500

I will be opening a PR for you to test in a moment.
