### ISSUE TITLE
Callback signature validation

### ISSUE THREAD

**Issue by rhytnen** [AllenInstitute/pigeon#3]
The callback signature for [`subscribe(...)`](https://github.com/AllenInstitute/pigeon/blob/master/pigeon/client.py#L153) and [`subscribe_all(...)`](https://github.com/AllenInstitute/pigeon/blob/master/pigeon/client.py#L173) should validate the signature of the callable immediately.

The current implementation will cause an exception at the time a message is received the callback is to be executed.  This allows a process to get arbitrarily deep into functioning before it is clear an error has occurred.  Validating in the subscription functions allow for an exception immediately, at the beginning of the process.

**Comment by CameronDevine** [comment]
I like this idea.

**Comment by CameronDevine** [comment]
This will have to wait until after we decide if we should merge #1 or not.

**Comment by rhytnen** [comment]
I can do a review of it in the morning if you want.

**Comment by CameronDevine** [comment]
If you could review it that would be great. If it looks good i'll throw in a receipt time as well.

**Comment by CameronDevine** [comment]
Closing since #1 was merged.
