### ISSUE TITLE
_handle_message should catch signature exceptions for the callback 

### ISSUE THREAD

**Issue by rhytnen** [AllenInstitute/pigeon#4]
I think that possibly, [`_handle_message)`](https://github.com/AllenInstitute/pigeon/blob/master/pigeon/client.py#L143) should handle the exception both from [`deserialize`](https://github.com/AllenInstitute/pigeon/blob/master/pigeon/client.py#L150) and [`_callbacks`](https://github.com/AllenInstitute/pigeon/blob/master/pigeon/client.py#L151) because the client code cannot handle these exceptions without applying a global hook.

Is the expected behavior that the client app should crash or use a global hook?  If the pigeon client handles the exception?  In the STOMP documentation, they provide an error handling callback for this purpose.  Testing the signature of the error handling callback at subscribe time (see issue #3), would allow you to forward error handling to the client in a way deemed safe at start up time.

**Comment by CameronDevine** [comment]
This is an excellent point. I think that I will add some `try`, `except` blocks around each of these calls. I think we should log the exception and continue. @dlbrittain, do you agree?

**Comment by dlbrittain** [comment]
I agree.
