### ISSUE TITLE
callback signature could contain additional parameters that are useful

### ISSUE THREAD

**Issue by rhytnen** [AllenInstitute/pigeon#5]
The signature of the callback function (`callback(topic: str, message: Frame)`) could include the client receive timestamp and a reference to the connection object.

This allows:
1.  Latency detection between sender and receiver (since the message header will contain an originating time stamp)
2.  Allows simpler access to the connection object so a callback may emit a message in response to receiving a request.  For example, a pair of messages likes `request_status` and `status`.

**Comment by CameronDevine** [comment]
This should be added to #1.

**Comment by CameronDevine** [comment]
Closing since #1 was merged.
